###################
# BUILD FOR STAGING SERVER
###################

FROM node:18-alpine As development

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

RUN rm .env.development.local

RUN npm run build

USER node

ENV NODE_ENV staging

EXPOSE 3030

CMD [ "npm", "run", "start:staging" ]
