version: '3.8'
# Docker compose file for test/staging server

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging

    volumes:
      - ../..:/workspaces:cached

    restart: unless-stopped

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 80:3000

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  redis:
    image: redis/redis-stack
    restart: unless-stopped
    volumes:
      - redis-data:/data
    network_mode: service:db

volumes:
  postgres-data:
  redis-data:
