version: '3.8'
# Docker compose file for test/staging server

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging

    volumes:
      - ../..:/workspaces:cached

    restart: unless-stopped
    ports:
      - 80:3030

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  redis:
    image: redis/redis-stack
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
