###################
# BUILD FOR STAGING SERVER
###################

FROM node:18-alpine As development

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

RUN npm run build

USER node

EXPOSE 3030

RUN npm run seed:refresh

CMD [ "npm", "run", "start:prod" ]
