export type Mailout =
  | 'password_reset'
  | 'account_delete'
  | 'email_change'
  | 'project_requested'
  | 'proposal_accepted'
  | 'unread_messages'
  | 'recent_needs'
  | 'recent_portfolios'
  | 'email_confirm'
  | 'welcome'
  | 'account_banned'
  | 'proposal_new'
  | 'project_complete_client'
  | 'project_complete_contractor';
