name: Checks
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install npm dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Run tests
      run: npm run test
    - name: Run e2e tests
      run: npm run test:e2e
    - name: Get code coverage
      run: npm run test:cov      
    - name: Update Coverage Badge
      # GitHub actions: default branch variable
      # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: we-cli/coverage-badge-action@main
